#!/bin/bash
set -e

echo "Проверяем наличие компилятора..."
if ! command -v g++ >/dev/null 2>&1; then
    echo "g++ не найден! Установите build-essential" >&2
    exit 1
fi

echo "Собираем программу через make..."
cd /usr/local/src/lab1v9/src
make install

echo "Установка завершена!"
